export const NEWS_CATEGORY_META = [
  {
    key: 'frontend',
    title: '前端技术',
    description: '更偏实现细节、浏览器能力和工程落地',
  },
  {
    key: 'ai',
    title: 'AI / 工程效率',
    description: '围绕模型能力、工作流和开发效率工具的快讯',
  },
  {
    key: 'product',
    title: '产品 / 商业',
    description: '关注产品策略、创作者经济和工具商业化',
  },
  {
    key: 'design',
    title: '设计 / UI',
    description: '设计系统、变量、组件协同和视觉趋势',
  },
  {
    key: 'industry',
    title: '行业热点',
    description: '适合快速知道今天大家在讨论什么，不负责替你下结论',
  },
];

export const NEWS_SOURCES = [
  {
    key: 'web-dev',
    title: 'Web.dev',
    category: 'frontend',
    type: 'rss',
    url: 'https://web.dev/feed.xml',
    sourceUrl: 'https://web.dev/',
    tags: ['前端技术', 'Web Platform'],
    limit: 6,
    weight: 1.2,
  },
  {
    key: 'css-tricks',
    title: 'CSS-Tricks',
    category: 'frontend',
    type: 'rss',
    url: 'https://css-tricks.com/feed/',
    sourceUrl: 'https://css-tricks.com/',
    tags: ['前端技术', 'CSS'],
    limit: 6,
    weight: 1.1,
  },
  {
    key: 'smashing-magazine',
    title: 'Smashing Magazine',
    category: 'frontend',
    type: 'rss',
    url: 'https://www.smashingmagazine.com/feed/',
    sourceUrl: 'https://www.smashingmagazine.com/',
    tags: ['前端技术', '设计/UI'],
    limit: 6,
    weight: 1.08,
  },
  {
    key: 'openai-news',
    title: 'OpenAI News',
    category: 'ai',
    type: 'rss',
    url: 'https://openai.com/news/rss.xml',
    sourceUrl: 'https://openai.com/news/',
    tags: ['AI', '模型产品'],
    limit: 6,
    weight: 1.15,
  },
  {
    key: 'hugging-face-blog',
    title: 'Hugging Face Blog',
    category: 'ai',
    type: 'rss',
    url: 'https://huggingface.co/blog/feed.xml',
    sourceUrl: 'https://huggingface.co/blog',
    tags: ['AI', '开源模型'],
    limit: 6,
    weight: 1.08,
  },
  {
    key: 'anthropic-news',
    title: 'Anthropic News',
    category: 'ai',
    type: 'rss',
    url: 'https://www.anthropic.com/rss.xml',
    sourceUrl: 'https://www.anthropic.com/news',
    tags: ['AI', '模型产品'],
    limit: 5,
    weight: 1.08,
  },
  {
    key: 'uxcollective',
    title: 'UX Collective',
    category: 'design',
    type: 'rss',
    url: 'https://uxdesign.cc/feed',
    sourceUrl: 'https://uxdesign.cc/',
    tags: ['设计/UI', '交互设计'],
    limit: 6,
    weight: 1.0,
  },
  {
    key: 'lenny',
    title: "Lenny's Newsletter",
    category: 'product',
    type: 'rss',
    url: 'https://www.lennysnewsletter.com/feed',
    sourceUrl: 'https://www.lennysnewsletter.com/',
    tags: ['产品/商业'],
    limit: 5,
    weight: 0.82,
  },
  {
    key: 'techcrunch',
    title: 'TechCrunch',
    category: 'product',
    type: 'rss',
    url: 'https://techcrunch.com/feed/',
    sourceUrl: 'https://techcrunch.com/',
    tags: ['产品/商业', '科技公司'],
    limit: 5,
    weight: 0.82,
  },
  {
    key: 'hacker-news',
    title: 'Hacker News',
    category: 'industry',
    type: 'api',
    url: 'https://hacker-news.firebaseio.com/v0/topstories.json',
    sourceUrl: 'https://news.ycombinator.com/',
    tags: ['行业热点', '工程效率'],
    limit: 8,
    weight: 1,
  },
  {
    key: 'github-blog',
    title: 'GitHub Blog',
    category: 'industry',
    type: 'rss',
    url: 'https://github.blog/feed/',
    sourceUrl: 'https://github.blog/',
    tags: ['行业热点', '开发平台'],
    limit: 5,
    weight: 0.95,
  },
  {
    key: 'product-hunt',
    title: 'Product Hunt',
    category: 'tools',
    type: 'rss',
    url: 'https://www.producthunt.com/feed',
    sourceUrl: 'https://www.producthunt.com/',
    tags: ['工具/网站', '新产品'],
    limit: 6,
    weight: 0.96,
  },
  // ---- 中文来源 ----
  {
    key: 'ruanyifeng',
    title: '阮一峰的网络日志',
    category: 'frontend',
    type: 'rss',
    url: 'http://www.ruanyifeng.com/blog/atom.xml',
    sourceUrl: 'https://www.ruanyifeng.com/blog/',
    tags: ['前端技术', '技术周刊'],
    limit: 6,
    weight: 1.18,
  },
  {
    key: 'zhangxinxu',
    title: '张鑫旭博客',
    category: 'frontend',
    type: 'rss',
    url: 'https://www.zhangxinxu.com/wordpress/feed/',
    sourceUrl: 'https://www.zhangxinxu.com/',
    tags: ['前端技术', 'CSS'],
    limit: 6,
    weight: 1.12,
  },
  {
    key: '75team',
    title: '奇舞周刊',
    category: 'frontend',
    type: 'rss',
    url: 'https://weekly.75.team/rss.xml',
    sourceUrl: 'https://weekly.75.team/',
    tags: ['前端技术', '技术周刊'],
    limit: 6,
    weight: 1.08,
  },
  {
    key: 'sspai',
    title: '少数派',
    category: 'tools',
    type: 'rss',
    url: 'https://sspai.com/feed',
    sourceUrl: 'https://sspai.com/',
    tags: ['工具/网站', '效率'],
    limit: 6,
    weight: 1.02,
  },
  {
    key: 'infoq-cn',
    title: 'InfoQ 中文',
    category: 'industry',
    type: 'rss',
    url: 'https://www.infoq.cn/feed',
    sourceUrl: 'https://www.infoq.cn/',
    tags: ['行业热点', '工程效率'],
    limit: 6,
    weight: 1.06,
  },
  {
    key: 'v2ex',
    title: 'V2EX 技术',
    category: 'industry',
    type: 'rss',
    url: 'https://www.v2ex.com/feed/tab/tech.xml',
    sourceUrl: 'https://www.v2ex.com/?tab=tech',
    tags: ['行业热点', '开发者社区'],
    limit: 6,
    weight: 0.95,
  },
];
