export const icons = [
  '/chushanxue/img/decorate/草莓.svg',
  '/chushanxue/img/decorate/樱桃.svg',
  '/chushanxue/img/decorate/樱桃布丁.svg',
  '/chushanxue/img/decorate/生日蛋糕.svg',
  '/chushanxue/img/decorate/包子.svg',
  '/chushanxue/img/decorate/茄子.svg',
  '/chushanxue/img/decorate/饺子.svg',
  '/chushanxue/img/decorate/牛奶.svg',
  '/chushanxue/img/decorate/西蓝花.svg',
  // '/img/decorate/甜甜圈.svg',
  // '/img/decorate/饮料.svg',
  // '/img/decorate/三明治.svg',
  // '/img/decorate/马卡龙.svg',
  // '/img/decorate/咖啡豆.svg',
  // '/img/decorate/红辣椒.svg',
  // '/img/decorate/彩色雪糕.svg',
  // '/img/decorate/汉堡.svg',
  // '/img/decorate/饼干.svg',
  // '/img/decorate/冰淇淋.svg',
];
